project:
  type: website

lang: es

website:
  title: "David González Martínez"
  site-url: "https://davidgmtz.github.io/DavidGM/"

  navbar:
    background: "#0b2d55"

    left:
      - href: index.qmd
        text: Inicio

      - href: proyectos.qmd
        text: Proyectos

      - href: about.qmd
        text: Sobre mí

    right:
      - icon: github
        aria-label: GitHub
        href: "https://github.com/DavidGMtz"

      - icon: linkedin
        aria-label: LinkedIn
        href: "https://www.linkedin.com/in/david-gonzalez-martinez-5729b7272"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true